spring.application.name=reading-companion-backend
spring.datasource.url=jdbc:mysql://localhost:3306/reading_companion
spring.datasource.username=rc_user
spring.datasource.password=password22


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



